#include "pch.h"
#include "BoxRenderer.h"
#include "BoxRenderer.g.cpp"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.

namespace winrt::Renderers::implementation
{
    Microsoft::UI::Xaml::DependencyProperty BoxRenderer::m_param0Property =
        Microsoft::UI::Xaml::DependencyProperty::Register(
            L"Param0", // name
            winrt::xaml_typename<int32_t>(),    // property type
            winrt::xaml_typename<Renderers::BoxRenderer>(), // owner type
            Microsoft::UI::Xaml::PropertyMetadata{ winrt::box_value(0), Microsoft::UI::Xaml::PropertyChangedCallback{ &BoxRenderer::OnParam0Changed } } // type metadata
    );
    Microsoft::UI::Xaml::DependencyProperty BoxRenderer::m_param1Property =
        Microsoft::UI::Xaml::DependencyProperty::Register(
            L"Param1", // name
            winrt::xaml_typename<int32_t>(),    // property type
            winrt::xaml_typename<Renderers::BoxRenderer>(), // owner type
            Microsoft::UI::Xaml::PropertyMetadata{ winrt::box_value(0), Microsoft::UI::Xaml::PropertyChangedCallback{ &BoxRenderer::OnParam1Changed } } // type metadata
    );

    void BoxRenderer::OnParam0Changed(Microsoft::UI::Xaml::DependencyObject const& d, Microsoft::UI::Xaml::DependencyPropertyChangedEventArgs const& /* e */)
    {
        if (Renderers::BoxRenderer theControl{ d.try_as<Renderers::BoxRenderer>() })
        {
            // Call members of the projected type via theControl.

            Renderers::implementation::BoxRenderer* ptr{ winrt::get_self<Renderers::implementation::BoxRenderer>(theControl) };
            // Call members of the implementation type via ptr.
        }
    }

    void BoxRenderer::OnParam1Changed(Microsoft::UI::Xaml::DependencyObject const& d, Microsoft::UI::Xaml::DependencyPropertyChangedEventArgs const& /* e */)
    {
        if (Renderers::BoxRenderer theControl{ d.try_as<Renderers::BoxRenderer>() })
        {
            // Call members of the projected type via theControl.

            Renderers::implementation::BoxRenderer* ptr{ winrt::get_self<Renderers::implementation::BoxRenderer>(theControl) };
            // Call members of the implementation type via ptr.
        }
    }
}
